# Generated by Django 2.1 on 2018-09-16 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20180916_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregaativa',
            name='ciclista',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Ciclista'),
        ),
    ]
