# Generated by Django 2.1 on 2018-09-16 19:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_merge_20180916_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregaativa',
            name='ciclista',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Ciclista'),
        ),
        migrations.AlterField(
            model_name='entregaativa',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
